# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Antonis Papadopoulos
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://antonispapadopoulos.art"

imagesurl: "/assets/images/"
thumbsurl: "/assets/thumbs/"


# Build settings
theme: hitchens-theme
plugins:
  - jekyll-feed

# hide_credits: true
hide_search: true

pictures:
- dimensions: "100x120"
  material: ""
  path: /assets/images/100x120m.jpg
- dimensions: "100x100"
  material: "Acrylic"
  path: /assets/images/4_100x100_acrylics.jpg
- dimensions: "80x80"
  material: "Acrylic"
  path: /assets/images/4_80x80_acrylics.jpg
- dimensions: "60x60"
  material: "Acrylic"
  path: /assets/images/60X60 _acrylic.jpg
- dimensions: "150x70"
  material: "Acrylic"
  path: /assets/images/150x70_acrylik_and_acrylic_ink_on_paper.jpg
- dimensions: ""
  material: ""
  path: /assets/images/IMG_0011.jpg
- dimensions: "100x100"
  material: "Acrylic"
  path: /assets/images/5_100x100_acrylics.jpg
- dimensions: "30x30"
  material: "Oil"
  path: /assets/images/30x30_oil.jpg
- dimensions: "30x30"
  material: "Acrylic"
  path: /assets/images/16_30x30_acrylics.jpg
- dimensions: "100x70"
  material: "Acrylic"
  path: /assets/images/100x70_acrylik_and_acrylic_ink_on_paper.jpg
- dimensions: "100x70"
  material: "Acrylic"
  path: /assets/images/3_100x70_acrylik_on_paper.jpg
- dimensions: "100x70"
  material: "Acrylic"
  path: /assets/images/6_100x70_acrylik_on_paper.jpg
- dimensions: "30x30"
  material: "Acrylic"
  path: /assets/images/4_30x30_acrylics.jpg
- dimensions: "30x30"
  material: "Acrylic"
  path: /assets/images/14_30x30_acrylics.jpg
- dimensions: "100x90"
  material: ""
  path: /assets/images/100x90.jpg
- dimensions: "140x120"
  material: "Oil on canvas"
  path: /assets/images/33_140x120_oil.jpg
- dimensions: "200x200"
  material: "Soft pastel on canvas"
  path: /assets/images/200x200.jpg
- dimensions: "100x70"
  material: "Acrylic ink on paper"
  path: /assets/images/2_100x70_acrylik_and_acrylic_ink_on_paper.jpg
- dimensions: "80x90"
  material: "Ink on paper"
  path: /assets/images/80x90.jpg
- dimensions: "100x120"
  material: "Coloured pencil on paper"
  path: /assets/images/100x120.jpg
- dimensions: "100x110"
  material: "Acrylics on canvas"
  path: /assets/images/first.jpg

